config/routes.rb
Affluence2::Application.routes.draw do

  

  
  resources :discussions, :only => [:index, :new, :create, :update] do
    end
  get "activities/index"

  get "activities/connections"

  get "offers/index"

  get "offers/new"

  get "offers/edit"

  get "offers/create"

  get "offers/update"

  get "offers/show"

  ActiveAdmin.routes(self)

  match 'home' => 'home#index'

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => 'passwords', :invitations => 'users/invitations'}
  devise_scope :user do
    get "/users/sign_in" => "welcome#index"

    get "/users/invitations/contacts" => "users/invitations#get_contacts", :as => :get_contacts
    post "/users/invitations/contacts" => "users/invitations#import_contacts", :as => :import_contacts

    match "/users/invitations/contacts_provider_callback" => "users/invitations#contacts_provider_callback", :as => :contacts_provider_callback

  end
 
  match "states_of_country", :to => "application#states_of_country"

  resources :users, :only => :show do
    resources :conversations, :only => [:index, :show, :new, :create, :update] do
      get :autocomplete_profile_full_name, :on => :collection
      get :archive
      get :unarchive
      get :confirm, :on => :collection
    end
    resources :photo_streams do
      post :create_photo
      delete 'photo/:id' => :destroy_photo, :as => 'photo'
    end
  end

  resources :photo_streams  

  resources :events do
    member do
      post :register
      get :delete_image
    end
    collection do
      get :home_page_events
      get :landing_page_events
      get :confirm
      get :events_schedules
    end
  end

  resources :home do

  end

  resources :verfications

  resources :photos

  resources :concierges do
    member do
      post :call
    end
  end

  resources :profiles  do
    collection do
      get :confirm
      get :confirm_credit_card_info
      get :profile_session
      get :check_avilability
      get :autocomplete_interest_name 
      get :autocomplete_expertise_name
      get :autocomplete_association_name
      get :update_notifications
      get :user_plan
      get :billing_info_confirm
      get :billing_info_update_confirm
      post :update_plan
      get :edit_privacy
      get :update_privacy
      get :cancel_membership
      get :delete_account
    end

    member do
      get :set_notification_complete
    end
  end

  resources :members, :except => [:show] do
    collection do
      get :latest
      get :find_members
      get :search
      get :delete_connection
    end
  end

  resources :offers do
    collection do
      get :latest
      get :confirm
    end
    member do
      get :activate
    end
  end

  resources :activities do
    collection do
      get :latest
    end
  end

  resources :orders
  resources :wineshares
  resources :welcome
  
  resources :twilio_calls do
    collection do
      get :receive_call
      post :status_call_back
    end
  end

  resources :promotions do
    member do
      get :become_premium_member
    end
  end

  match "api/user/sign_in" => "api#user_sign_in", :ssl => :required
  match "api/postback" => "api#postback", :ssl => :required
  match "api/callback_test" => "api#callback_test", :ssl => :required
  post "api/vincompass/validate_tokens" => "api#validate_tokens", :ssl => :required
  post "api/vincompass/authorize/application" => "api#authorize_application", :ssl => :required
  post "api/vincompass/authorize/user" => "api#authorize_user", :ssl => :required
  post "api/vincompass/activity_post" => "api#activity_post", :ssl => :required
  post "api/vincompass/v2/activity_post" => "api#activity_post_v2", :ssl => :required

  root :to => 'welcome#index'

  match '*url' => 'welcome#index'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  paginates_per 5
  has_many :messages, :order => "created_at"
  has_many :conversation_metadata, :dependent => :destroy
  has_many :interactions, :dependent => :destroy
  
  scope :for_user, lambda { |user|
    joins(:conversation_metadata).
        includes(:messages).
        where("conversation_metadata.user_id = ?", user.id).
        order("messages.updated_at DESC")
  }

  # at least one message in the conversation was sent to user
  scope :for_recipient, lambda { |user|
    joins(:conversation_metadata).
        includes(:messages).
        where("conversation_metadata.user_id = ? AND messages.recipient_id = ?", user.id, user.id)
  }

  scope :archived?, lambda { |is_archived|
    joins(:conversation_metadata).
        where("conversation_metadata.archived = ?", is_archived)
  }

  scope :read?, lambda { |is_read|
    joins(:conversation_metadata).
        where("conversation_metadata.read = ?", is_read)
  }


  accepts_nested_attributes_for :messages
  # attr_accessible :messages_attributes

  # the user <user> is having a conversation with.

   #Usage call with the current-user and the text as the query to be searched
   def self.matching_conversation(user_id,query)
     find_by_sql(["
     with selected_user_ids as
        (
          select distinct user_id
          from profiles
          where (user_id is not null)
                and ( to_tsvector('english', COALESCE(first_name,'') || ' ' || COALESCE(last_name,'')) @@ plainto_tsquery('english', ?))
        )
        select id from (
          select conversation_id as id  ,rank() over (partition by conversation_id order by created_at desc) as internal_rank
          from messages
          where  ((sender_id=? and recipient_id in (select * from selected_user_ids) ) or  (recipient_id=? and sender_id in (select * from selected_user_ids) ))
        ) matching_users
        where internal_rank=1

        union

        select id from (
          select distinct messages.conversation_id as id  ,rank() over (partition by conversation_id order by created_at desc) as internal_rank
          from messages
          where to_tsvector('english', COALESCE(subject,'') || ' ' || COALESCE(body,''))  @@ plainto_tsquery('english', ?)
                and  (sender_id=? or recipient_id=?)
        ) matching_subs_body
        where internal_rank = 1
        limit 100
     ",query,user_id,user_id,query,user_id,user_id])
   end
  

  def recipient_for(user)
    results = messages.where(:sender_id => user.id)
    if !results.empty?
      results.first.recipient
    else
      messages.first.sender
    end
  end

  def archive!(user)
    conversation_metadata.where(:user_id => user.id).each do |meta|
      meta.update_attribute(:archived, true)
    end
  end

  def unarchive!(user)
    conversation_metadata.where(:user_id => user.id).each do |meta|
      meta.update_attribute(:archived, false)
    end
  end

  def mark_as_read!(user)
    conversation_metadata.where(:user_id => user.id).each do |meta|
      meta.update_attribute(:read, true)
    end
  end

  def archived?(user)
    result = conversation_metadata.where(:user_id => user.id, :archived => true)
    !result.empty?
  end

  def read?(user)
    result = conversation_metadata.where(:user_id => user.id, :read => true)
    !result.empty?
  end

  def self.get_conversation_for(*args)
    temp = "select distinct conversation_id as id from conversation_metadata
             where user_id = "
    query = ""
    args.each do |id|
      query = query + temp + id.to_s
      unless (args.last == id)
        query = query + " intersect "
      end
    end

    result = find_by_sql(query)
    if result.size > 1
      unless result.blank?
        conversation_ids = []

        result.each do |conv|
          conversation_ids << conv.id
        end

        query = "select conversation_id as id from conversation_metadata
 where conversation_id in (#{conversation_ids.join(',')})
 group by conversation_id
 having count(user_id)=#{result.size}"
        result = find_by_sql(query)
      end
    end
    result
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_conversation_resource, :except => [:index, :show, :confirm]
  before_filter :set_page_header, :update_unread_messages_count
  autocomplete :profile, :full_name, :extra_data => [:id]


  def authorize_conversation_resource
    begin
      authorize! :all, :conversation
    rescue CanCan::AccessDenied
      flash[:error] = "Messaging is restricted to verified or premium members. Become a premium member
          #{ActionController::Base.helpers.link_to "Register", edit_profile_path(current_user.permalink, :value => 'billing info')}".html_safe
      redirect_to(:back)
    end
  end

  def get_autocomplete_items(parameters)
    items = super(parameters)
    items = Profile.joins(:user).where("LOWER(profiles.full_name) ilike ? and status = ?  and role = ?  and user_id != ?", "#{params[:term]}%", "active", "member", current_user.id).order("profiles.full_name").limit(10).select(["profiles.id", "profiles.full_name"])
  end

  def index
    @archived = to_bool(params[:saved])
    @conversation = Conversation.new
    @conversation.messages.build
    @searched = !params[:search].blank?

    if !params[:search].blank?
      conversations = Conversation.matching_conversation(current_user.id, params[:search])
      @conversations = Kaminari.paginate_array(conversations).page(params[:page]).per(10)
    else
      @conversations = Conversation.joins(:conversation_metadata).where("conversation_metadata.user_id = ?", current_user.id).archived?(@archived).order("updated_at DESC").page params[:page]
    end
  end

  def new
    @conversation = Conversation.new
    if @recipient = Profile.find_by_id(params[:to]).user rescue nil
      @conversation.messages.build(:recipient => @recipient)
    else

      @conversation.messages.build
    end
  end

  def show
    @conversations = Conversation.for_user(current_user)
    @conversation = Conversation.find(params[:id], :include => :messages)
    if @conversations.include? @conversation

      status = @conversation.archived?(current_user)
      @replies = Message.get_ordered_messages_for_conversation(@conversation.id)

      @conversation.messages.build
      unless @conversation.read?(current_user)
        session[:unread_messages_count] -= 1 if @conversation.mark_as_read!(current_user)
      end
    elsif Ability.new(current_user).can?(:all, :conversation)
      flash[:error] = "Messaging is restricted to verified or premium members. Become a premium member."
    else
      redirect_to user_conversations_path(current_user), :flash => {:error => "Unauthorized Access!"}
    end
  end

  def create
    recipient_user = Profile.find(params[:conversation][:recipient_profile_id])[0].user rescue nil
    params[:conversation].delete(:recipient_profile_id)
    if !recipient_user.blank? && recipient_user.profile.full_name == params[:conversation_recipient_profile_name]

      @conversation = Conversation.get_conversation_for(current_user.id, recipient_user.id).first
      if @conversation.nil?
        @conversation = Conversation.new(params[:conversation])

      else
        #      @conversation = message.conversation
        @conversation.messages << Message.new(params[:conversation][:messages_attributes]["0"])

      end

      @conversation.messages.last.sender = current_user
      @conversation.messages.last.recipient = recipient_user
      #      ConnectionRequest.find_or_create_by_requestor_id_and_requestee_id(current_user.id, recipient_user.id)

      #      authorize!(:create, @conversation.messages.first)

      if @conversation.save
        redirect_to user_conversations_path(current_user), :flash => {:success => "Your message has been sent."}
      else
        render :new
      end
    else
      @conversation = Conversation.new
      @conversation.messages.build
      flash[:error] = "Cannot send message to that user or user does not exist."
      render :new
    end
  end

  def update

    @conversation = Conversation.find(params[:id])
    #    @conversation = Conversation.get_conversation_for(current_user.id, recipient_user.id).first

    recipient = @conversation.recipient_for(current_user)

    #    authorize! :edit, @conversation
    previous_message = @conversation.messages.last
    new_message_attrs = {}
    new_message_attrs[:body] = params[:message][:body]
    new_message_attrs[:subject] = params[:message][:subject]
    new_message_attrs[:sender_id] = current_user.id
    new_message_attrs[:recipient_id] = recipient.id
    new_message_attrs[:conversation_id] = @conversation.id

    #    if previous_message.sender_id != current_user.id
    #      Connection.make_connection(current_user, recipient)
    #      Connection.make_connection(recipient, current_user)
    #    end
    #
    #
    ##    authorize!(:create, Message)

    already_connected = Connection.are_connected?(recipient.id, current_user.id)

    if @message = Message.create(new_message_attrs)
      @conversation.messages << @message
      @conversation.save
      newly_connected = ((!already_connected) ? Connection.are_connected?(@message.sender_id, @message.recipient_id)  : false )
      if newly_connected
        reset_session_activity
      end
      redirect_to user_conversations_path(current_user), :flash => {:success => "Your message has been sent."}
    else
      render :show
    end
  end

  def archive
    @conversation = Conversation.find(params[:conversation_id])
    unread_messages_count = ConversationMetadatum.where(:user_id => current_user.id, :read => false).size
    current_user.update_attributes(:unread_messages_counter => unread_messages_count)
    #    authorize! :edit, @conversation
 
    @conversation.archive!(current_user)

    respond_to do |format|
      format.html { redirect_to user_conversations_path(current_user), :flash => {:success => "Conversation has been archived."} }
      format.js { render :layout => false }
    end
  end

  def unarchive
    @conversation = Conversation.find(params[:conversation_id])

    authorize! :edit, @conversation

    @conversation.unarchive!(current_user)

    respond_to do |format|
      format.html { redirect_to user_conversations_path(current_user), :flash => {:success => "Conversation has been unarchived."} }
      format.js { render :nothing => true }
    end
  end

  # will be called when free user tries to subscribe before offer activation.
  def confirm
    begin
      @result = Braintree::TransparentRedirect.confirm(request.query_string)
      if @result.success?
        current_user.update_user_with_plan_and_braintree_id(session[:user_plan], @result.customer.id)
        session[:user_plan]=nil
        flash[:success] = "You have successfully converted to paid member. Now you can send messages"
        redirect_to user_conversations_path(current_user.id)
      else
        flash[:error] = "Your payment was not success. Check your card information."
        redirect_to user_conversations_path(current_user.id)
      end
    rescue
      flash[:error] = "Your payment was not success. Check your card information."
      redirect_to user_conversations_path(current_user.id)
    end
  end


  private
  def set_page_header
    @page_header = "Messages"
  end


end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def to_hash_with_subject_as_keys(replies)
    temp = {}
    replies.each do |reply|
      temp[reply.subject] = [] if temp[reply.subject].nil?
      temp[reply.subject] << reply
    end
    return temp
  end
end

app/views/conversations/_last_message.haml
- messages = Message.get_ordered_messages_for_conversation(conversation.id)

- unless conversation.messages.blank?
  - message = conversation.messages.last
  - if !conversation.messages.where('sender_id = ? and recipient_id != ?', current_user, current_user).last.blank?
    - profile = conversation.messages.where('sender_id = ? and recipient_id != ?', current_user, current_user).last.recipient.profile
  - else
    - profile = conversation.messages.last.sender.profile
  %tr{:class => "#{'unread' unless conversation.read?(current_user)}" }
    %td.span1{:data => {:conversation_id => conversation.id}}
      =# profile.user.id
      = link_to image_tag(display_image(profile.photos, :thumb)), user_conversation_path(current_user, conversation), :class => "thumbnail"
    %td
      -if conversation.messages.length > 1
        %h5{:class => "#{'unread_msg' unless conversation.read?(current_user)} tk-ff-tisa-web-pro" }
          Last reply by <span>#{last_reply_name(conversation.messages.last.sender)}:</span>
      -else
        %span{:class => "#{'unread_msg' unless conversation.read?(current_user)} last-reply tk-ff-tisa-web-pro" }
          = link_to message.sender.profile.full_name, user_conversation_path(current_user, conversation), :class => "desc"
      %br/
    %td= time_ago_in_words(message.updated_at) + " ago"
    %td
      - if !searched && !archived
        %a.close{:href => "#{user_conversation_archive_path(current_user, conversation)}",
                 :rel => "tooltip",
                 "data-confirm" => 'Are you sure?',
                 "data-original-title" => "Archive",
                 "data-placement" => "bottom"}archive
  %tr
    %td{:colspan => 4}
      %p
        - hash_of_replies = to_hash_with_subject_as_keys(messages)
        - temp = 0
        .accordion{:id => "accordion#{conversation_index}"}
          - hash_of_replies.each_pair do |subject, messages|
            .accordion-group
              .accordion-heading
                %a.accordion-toggle{"data-parent" => "#accordion#{conversation_index}", "data-toggle" => "collapse", :href => "#collapse#{conversation_index}#{temp}"}
                  = subject
              .accordion-body.collapse{:id => "collapse#{conversation_index}#{temp}", :class => "#{(temp > 0)? '' : 'in'}"}
                .accordion-inner
                  %table
                    - messages.reverse.each do |reply|
                      %tr
                        %td
                          = link_to image_tag(display_image(reply.sender.profile.photos, :thumb)), user_conversation_path(current_user, conversation), :class => "thumbnail"
                        %td
                          = reply.body 
                        %td= time_ago_in_words(message.updated_at) + " ago"
                    %tr
                      %td
                      %td
                        - conversation.messages.build
                        = semantic_form_for conversation, :url => user_conversation_path(current_user, conversation) do |f|
                          = semantic_fields_for :message do |m|
                            = m.inputs do
                              = m.input :subject, :as => :hidden, :label => false, :input_html => { :value => subject,:placeholder => "Your comment...", :rows => "5", :style => "width:370px;"}
                              = m.input :body, :as => :text, :label => false, :input_html => {:placeholder => "Your comment...", :rows => "5", :style => "width:370px;"}
                          = f.buttons do
                            = f.commit_button "Reply", :button_html => {:class => "btn btn-primary", :id => nil}


            - temp = temp + 1

app/views/conversations/_message_reply.haml
-if message.sender
  .reply{ :id => "message_#{message.id}" }
    .margin
      = link_to image_tag(message.sender.profile.photos.first.image.url(:avatar)), profile_path(message.sender), :class => "avatar small"
      %span.spinner= image_tag("ajax-loader.gif")
    .main
      .entry-title
        = link_to message.sender.profile.name, profile_path(message.sender), :class => "author vcard fn url"
      .comment-content= message_with_links_and_paragraphs(message.body).html_safe
      .byline
        %abbr.published= time_ago_in_words(message.created_at) + " ago"

app/views/conversations/_page_header.haml
#page-header
  -if controller.action_name == "new"
    %header#title
      =link_to "message", user_conversations_path(current_user), :class=>"msg"
      %h1= 'New Message'
  -if controller.action_name == "show"
    %header#title.conversations-header
      =link_to "message", user_conversations_path(current_user), :class=>"msg view_msg"
      %h1 View Messages
      - convo_index = @other_conversations.index(@conversation)
      -if convo_index > 0 && @other_conversations[convo_index - 1]
        =link_to "up", user_conversation_path(current_user, @other_conversations[convo_index - 1]), :class=>"up"
      -else
        %a{:href => "#", :class => "up disabled"} up
      -if @other_conversations[convo_index + 1]
        =link_to "down", user_conversation_path(current_user,@other_conversations[convo_index + 1]), :class=>"down"
      -else
        %a{:href => "#",:class => "down disabled"} down
      .clear
  -else
    %h3.page-title{:class => @page_header.downcase}
      =@page_header
    -unless controller.action_name == "new"
      .new-message
        = link_to 'New Message', new_user_conversation_path(current_user)

-unless controller.action_name == "show" || controller.action_name == "new"
  .messages-tabs
    = tabs_tag :open_tabs => { :class => "section #{current_tab}", :role => 'navigation' }, :namespace => :messages do |tab|
      = tab.inbox "Inbox", user_conversations_path(current_user, :tab_page => "inbox"), :class=> "inbox"
      %a.msg_counter{:class => "#{'doubledigit' if unread_messages_count > 9}"}=unread_messages_count
      = tab.archive "Archive", user_conversations_path(current_user, :tab_page => "archive"), :class=> "archive"
    .archive
      %p.select
        Select
        %a{:href => "#"} All
        %a{:href => "#"} None
      %img{:src => "/images/archive_seperator.png"}
      %p.archive_text With selected:
      - if params[:tab_page] == "archive"
        %a{:href => "#", :class => "unarchive_btn"} Unarchive
      - else
        %a{:href => "#", :class => "archive_btn"} Archive
      .clear

app/views/conversations/archive.js.haml
-unless @conversation.read?(current_user)
  -session[:unread_messages_count] -= 1 if @conversation.mark_as_read!(current_user)
  var count = "#{session[:unread_messages_count]}";

  $("nav .msg_counter").html(count);
  $(".inbox .count").html(count);

app/views/conversations/index.html.haml
.span9
  .row
    .span5
      %h2 Messages
    .span4
      %p.pull-right
      .span4
        .btn-group.pull-right{"data-toggle" => "buttons-radio"}
          = link_to 'inbox', user_conversations_path("saved" => false), {:class => "conversations_type btn btn-small btn-primary #{@searched ? '' : !@archived ? 'active' : ''}"}
          = link_to 'archived', user_conversations_path("saved" => true), {:class => "conversations_type btn btn-small btn-primary #{@archived ? 'active' : ''}"}
        %a.btn.btn-primary{"data-toggle" => "modal", :href => "#new-message", :id => "conversation_#{current_user.id}", :class => "conversation-register-button"}
          %i.icon-pencil.icon-white
          New Message
  = form_tag user_conversations_path, {:method => :get, :id => "search"  } do
    = text_field_tag :search, params[:search], :placeholder => "Search ... ", :id => 'term', :class => "input-xlarge span7", :size => "20x1"
    = submit_tag "search", :class => "btn"


  -unless @conversations.blank?
    - @conversations.each_with_index do |conversation, index|
      - unless conversation.messages.blank?
        - message = conversation.messages.last
        .accordion{:id => "accordion_conversation_#{index}"}
          .accordion-group
            .accordion-heading
              .span9
                .span1
                .span5
                  %a.accordion-toggle{"data-parent" => "#accordion_conversation_#{index}", "data-toggle" => "collapse", :href => "#collapse_conversation_#{index}"}
                    = message.subject 
                .span3.pull-right
                  = time_ago_in_words(message.updated_at) + " ago"
            .accordion-body.collapse{:id => "collapse_conversation_#{index}"}
              .accordion-inner
                =render :partial => "conversations/last_message", :locals => {:conversation => conversation, :archived => @archived, :searched => @searched, :conversation_index => index}
    = paginate(@conversations, :theme => "bootstrap")

  -else
    %p.no-messages No Messages

- if Ability.new(current_user).cannot?(:all,:conversation)
  #new-message.modal.hide.fade.in{:style => "display: none;"}
  :javascript
     $('.conversation-register-button').click(function(){
       var user_id = this.id.split('_')[1]
       //alert(event_id) ;
       $.ajax({
                     url: "/promotions/"+user_id+"/become_premium_member",
                     data:'promotion=conversation',
                     //async: false,
                     success:function(data){
                       $('#new-message').html(data);
                       //alert('Load was performed.');
                     },
                     dataType:'html'
                     });
       //$('#register-div').modal('show');
     });
- else
  #new-message.modal.hide.fade.in{:style => "display: none;"}
    .modal-header
      %a.close{"data-dismiss" => "modal", :href => "#"} ×
      %h3 New Message
    .modal-body
      = form_for @conversation, :url => user_conversations_path(current_user), :html => { :class => "form-horizontal" } do |f|
        %fieldset
          = f.fields_for :messages, :html => { :multipart => true } do |x|
            .control-group
              %label.control-label{:for => "fileInput"} To
              .controls
                %ul#msg_to{:name => "recipient_profile_id"}
            .control-group
              %label.control-label{:for => "fileInput"} Subject
              .controls
                = x.text_field :subject, :placeholder => "Subject ....", :class => "input ", :rows => "5", :style => "width:370px;"
            .control-group
              %label.control-label{:for => "fileInput"} Body
              .controls
                = x.text_area :body, :placeholder => "Write message ....", :class => "input ", :rows => "5", :style => "width:370px;"
                = hidden_field_tag :conversation_recipient_profile_name, "", :class => "input "
          .control-group
            .controls
              = f.submit "Send Message", :class => "btn btn-primary"

  -content_for :javascripts do
    =javascript_include_tag("tag-it/tag-it")
    :javascript
      $(function() {
        var to_member = #{params[:to].present?};
        var recipient_name = "#{@recipient ? @recipient.profile.name : ''}"
        var recipient_profile_id = "#{@recipient? @recipient.profile.id : ''}"
        var profile_id;
        $("#msg_to").tagit({
          itemName: 'conversation',
          tagSource: function(request,response){
            $.ajax({
              url: "#{autocomplete_profile_full_name_user_conversations_path(current_user)}",
              dataType: "json",

              data: {
                term: request.term
              },
              beforeSend: function(jqXHR, settings){
                $(".new_msg_form").find(".ajax-loader").fadeIn();
              },
              success: function( data ) {
                $(".new_msg_form").find(".ajax-loader").fadeOut();
                response($.map(data, function(item){
                  profile_id = item.id
                  if($("#msg_to").children().length < 2){
                    return {
                      label: item.value,
                      value: item.value,
                      profile_id: item.id

                    }
                  }
                }))
              }
            });
          },
          fieldName: 'recipient_profile_id',
          onTagAdded: function(el) {
            $(el).find('input').val($(el).attr('data-profile_id'));
            var user_name = el.text().substring(0, el.text().length-1);
            $("#conversation_recipient_profile_name").val(user_name);
            $("#msg_to .tagit-new input").attr("disabled", "true");
            $("#conversation_messages_attributes_0_subject").focus();
            $("#msg_to .tagit-new input").css('display', 'none');


          },
          onTagRemoved: function(el) {
            $("#msg_to .tagit-new input").css('display', 'block');
            $("#msg_to .tagit-new input").removeAttr("disabled");
          },
          select: true,
          allowSpaces: true,
          caseSensitive: false
        });
        if(to_member){
          $("#msg_to").prepend("<li class=\"alert-info alert\">"+recipient_name +"<a class=\"close\">x</a><input type=\"hidden\" style=\"display:none;\" value=\""+recipient_profile_id+"\" name=\"conversation[recipient_profile_id][]\"></li>")
        }
      });

app/views/conversations/show.html.haml
.span9
  .row
    .span5
      %h2 Messages


  -unless @replies.blank?
    %table.table.table-striped
      %tbody
        - hash_of_replies = to_hash_with_subject_as_keys(@replies)
        - hash_of_replies.each_pair do |subject, messages|
          - messages.reverse.each do |reply|
            - if reply.sender
              %tr
                %td.span1
                  -if reply.sender.profile.user.member?
                    = link_to image_tag(display_image(reply.sender.profile.photos, :thumb)), profile_path(reply.sender.permalink), :class => "avatar large"
                  -else
                    = image_tag(display_image(reply.sender.profile.photos, :thumb))
                %td
                  %h5
                    -if reply.sender.profile.user.member?
                      =link_to reply.sender.profile.name, profile_path(reply.sender.permalink)
                    -else
                      = reply.sender.profile.name
                  %br/
                  %p
                    = message_with_links_and_paragraphs(reply.body).html_safe
                %td= reply.subject
                %td= time_ago_in_words(reply.updated_at) + " ago"
          %tr
            %td.span1
              = link_to image_tag(display_image(current_user.profile.photos, :thumb)), profile_path(current_user.permalink), :class => "avatar small"
            %td
              = semantic_form_for @conversation, :url => user_conversation_path do |f|
                = semantic_fields_for :message do |m|
                  = m.inputs do
                    = m.input :subject, :as => :hidden, :label => false, :input_html => { :value => subject,:placeholder => "Your comment...", :rows => "5", :style => "width:370px;"}
                    = m.input :body, :as => :text, :label => false, :input_html => {:placeholder => "Your comment...", :rows => "5", :style => "width:370px;"}
                = f.buttons do
                  = f.commit_button "Send", :button_html => {:class => "btn btn-primary", :id => nil}
          %tr.span7
            %td
              %hr