config/routes.rb
Affluence2::Application.routes.draw do

  

  
  resources :discussions, :only => [:index, :new, :create, :update] do
    end
  get "activities/index"

  get "activities/connections"

  get "offers/index"

  get "offers/new"

  get "offers/edit"

  get "offers/create"

  get "offers/update"

  get "offers/show"

  ActiveAdmin.routes(self)

  match 'home' => 'home#index'

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => 'passwords', :invitations => 'users/invitations'}
  devise_scope :user do
    get "/users/sign_in" => "welcome#index"

    get "/users/invitations/contacts" => "users/invitations#get_contacts", :as => :get_contacts
    post "/users/invitations/contacts" => "users/invitations#import_contacts", :as => :import_contacts

    match "/users/invitations/contacts_provider_callback" => "users/invitations#contacts_provider_callback", :as => :contacts_provider_callback

  end
 
  match "states_of_country", :to => "application#states_of_country"

  resources :users, :only => :show do
    resources :conversations, :only => [:index, :show, :new, :create, :update] do
      get :autocomplete_profile_full_name, :on => :collection
      get :archive
      get :unarchive
      get :confirm, :on => :collection
    end
    resources :photo_streams do
      post :create_photo
      delete 'photo/:id' => :destroy_photo, :as => 'photo'
    end
  end

  resources :photo_streams  

  resources :events do
    member do
      post :register
      get :delete_image
    end
    collection do
      get :home_page_events
      get :landing_page_events
      get :confirm
      get :events_schedules
    end
  end

  resources :home do

  end

  resources :verfications

  resources :photos

  resources :concierges do
    member do
      post :call
    end
  end

  resources :profiles  do
    collection do
      get :confirm
      get :confirm_credit_card_info
      get :profile_session
      get :check_avilability
      get :autocomplete_interest_name 
      get :autocomplete_expertise_name
      get :autocomplete_association_name
      get :update_notifications
      get :user_plan
      get :billing_info_confirm
      get :billing_info_update_confirm
      post :update_plan
      get :edit_privacy
      get :update_privacy
      get :cancel_membership
      get :delete_account
    end

    member do
      get :set_notification_complete
    end
  end

  resources :members, :except => [:show] do
    collection do
      get :latest
      get :find_members
      get :search
      get :delete_connection
    end
  end

  resources :offers do
    collection do
      get :latest
      get :confirm
    end
    member do
      get :activate
    end
  end

  resources :activities do
    collection do
      get :latest
    end
  end

  resources :orders
  resources :wineshares
  resources :welcome
  
  resources :twilio_calls do
    collection do
      get :receive_call
      post :status_call_back
    end
  end

  resources :promotions do
    member do
      get :become_premium_member
    end
  end

  match "api/user/sign_in" => "api#user_sign_in", :ssl => :required
  match "api/postback" => "api#postback", :ssl => :required
  match "api/callback_test" => "api#callback_test", :ssl => :required
  post "api/vincompass/validate_tokens" => "api#validate_tokens", :ssl => :required
  post "api/vincompass/authorize/application" => "api#authorize_application", :ssl => :required
  post "api/vincompass/authorize/user" => "api#authorize_user", :ssl => :required
  post "api/vincompass/activity_post" => "api#activity_post", :ssl => :required
  post "api/vincompass/v2/activity_post" => "api#activity_post_v2", :ssl => :required

  root :to => 'welcome#index'

  match '*url' => 'welcome#index'
end

app/views/shared/_billing_info.haml
.modal.hide.fade{:style => "display: none; min-height: 585px; top: 45%;", :id => div_id}

app/views/shared/_braintree_error_messages.html.haml
- if @result && @result.errors.any?
  #errorExplanation.alert.alert-error
    %a.close{"data-dismiss" => "alert"}×
    %h4.alert-heading
      = pluralize(@result.errors.for(:customer).for(:credit_card).size, "error")
      prohibited  from being saved:
    %ul
      - @result.errors.for(:customer).for(:credit_card).each do |error|
        %li= error.message

app/views/shared/_error_messages.html.haml
- if target.errors.any?
  #errorExplanation.alert.alert-error
    %a.close{"data-dismiss" => "alert"}×
    %h4.alert-heading
      = pluralize(target.errors.count, "error")
      prohibited  from being saved:
    %ul
      - target.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_message.html.haml
- flash.each do |key, msg|
  .alert{:class => "alert-#{key} flash"}
    %a.close{"data-dismiss" => "alert"}×
    = content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}"
    = content_tag :script, :type => "text/javascript" do
      setTimeout(function() { $('.flash').fadeOut(1600); }, 5000);

app/views/shared/_footer.html.haml
%hr
  %footer
    %p © Company 2012

app/views/shared/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Affluence",root_path, :class => "brand"
      .nav-collapse
        %ul.nav
          %li{:class => "#{'active' if home?}"}
            %a{:href => "/home"} Home
          %li{:class => "#{'active' if events?}"}
            %a{:href => "/events"} Events
          %li{:class => "#{'active' if offers?}"}
            %a{:href => "/offers"} Offers
          %li{:class => "#{'active' if gives?}"}
            %a{:href => "#"} Gives
          - if current_user && current_user.superadmin?
            %li{:class => "#{'active' if gives?}"}
              %a{:href => "#{admin_dashboard_path}"} Dashboard
        %ul.nav.pull-right
          %li#menu1.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#menu1"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'Settings', edit_profile_path(current_user.permalink)
              %li
                = link_to 'Privacy', edit_privacy_profiles_path
              %li
                = link_to "Order History", orders_path
              %li.divider
              %li
                = link_to 'Sign Out', destroy_user_session_path, :method => :delete

  :javascript
    $(function(){
      $('.dropdown-toggle').dropdown();
    });

app/views/shared/_member.html.haml
%li.span1
  %div
    .thumbnail-div
      %a.image-a-link.thumbnail{"data-original-title" => "#{member.profile.full_name}", "data-placement" => "bottom", :href => "#{profile_path(member.permalink)}", :rel => "tooltip"}
        = image_tag display_image(member.profile.photos, :thumb)
        - if member.verified?
          %span.image-link-span
        - unless @total.nil?
          %span.tickets-link-span
            = "+#{@total}"

app/views/shared/_new_message.html.haml
#new-message.modal.hide.fade.in{:style => "display: none;"}
  .modal-header
    %a.close{"data-dismiss" => "modal", :href => "#"} ×
    %h3 New Message
  .modal-body
    %form.form-horizontal
      %fieldset
        .control-group
          %label.control-label{:for => "input01"} To
          .controls
            <input type="text" profita"]"="" stukel","michael="" macleod","doug="" blake="" data-source="[" data-input="5" data-provide="typeahead" id="input01" class="input-xlarge">
        .control-group
          %label.control-label{:for => "textarea"} Message
          .controls
            %textarea#textarea.input-xlarge{:rows => "3"}
        .form-actions
          %button.btn.btn-primary{:type => "submit"} Send

    = semantic_form_for(@conversation, :url => user_conversations_path) do |f|
      = f.inputs do
        = f.fields_for(:messages) do |m|
          %li.string.input.msg-input
            %label To:
            .recepients
              %ul#msg_to{:name => "recipient_profile_id"}
            .ajax-loader Searching Members...
          = m.input :subject, :input_html => { :class => 'send_msg_input' }
          = m.input :body, :label => "Message", :input_html => {:rows => 10}
          = m.input :recipient_name, :as => :hidden, :input_html =>{:id => "msgRecip", :value => "#{@recipient.profile.name if @recipient}"}
      = f.buttons do
        = f.commit_button "Send Message", :button_html => {:class => "new_msg_send"}

app/views/shared/_notification_tracker_alert.html.haml
- notifications = current_user.pending_alert_notifications
- if !notifications.blank?
  - notifications.each do |notification|
    .alert{:class => "alert-info"}
      %a.close{"data-dismiss" => "alert", :id=> "notification_tracker_#{notification}"}×
      = content_tag :div, notification.subject, :class => ["info", " message"], :id => "notice_info"


    :javascript
      $(function () {
        $("#notification_tracker_#{notification}").click(function(){
        var notification_id = #{notification};
          alert('hai');

               $.ajax({
                      type : 'get',
                      url : '/profiles/'+notification_id+'/set_notification_complete',
                      datatype : 'json',
                      //data : email,
                      headers: {
                           'X-Transaction': 'POST Example',
                           'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                         },
                      success : function(data) {

                      },
                      error : function(data){

                      }
                    });
           });

      });

app/views/shared/_profile_navigation.html.haml
.span3
  %div
    .member-div
      %a.image-a-link
        = image_tag display_image(@profile.nil? ? current_user.profile.photos : @profile.photos, :medium)
        - if (@profile.nil? ? current_user.verified? : @profile.user.verified?)
          %span.image-link-span
  .well
    %ul.nav.nav-list
      %li.nav-header Socialize
      %li{:class => "#{params[:controller] == "home" ? "active":""}"}
        %a{:href => "/home"}
          %i.icon-star>
          What's New
      %li{:class => "#{'active' if profiles?}"}
        %a{:href => "#{profile_path(current_user.permalink)}"}
          %i.icon-home>
          Profile
      %li{:class => "#{(params[:controller] == 'photo_streams') ? 'active':''}"}
        %a{:href => "#{user_photo_streams_path(current_user.permalink)}"}
          %i.icon-picture>
          Photo Stream
      %li{:class => "#{(params[:controller] == 'members') ? 'active':''}"}
        %a{:href => "#{search_members_path}"}
          %i.icon-user>
          Members
      %li{:class => "#{(params[:controller] == 'discussions') ? 'active':''}"}
        %a{:href => "#{discussions_path}"}
          %i.icon-comment>
          Discussions
      %li{:class => "#{(params[:controller] == 'conversations') ? 'active':''}"}
        %a{:href => "#{user_conversations_path(current_user)}"}
          %i.icon-inbox>
          Messages
          - if (unread_messages_count > 0)
            %span{:class => "label label-important"}
              = unread_messages_count
      %li
        %a{:href => "#"}   
          %i.icon-glass>
          Concierge
      %li{:class => "#{(params[:controller] == 'invitations') ? 'active':''}"}
        %a{:href => "#{new_user_invitation_path}"}
          %i.icon-envelope>
          Invites
  / side bar nav
  %div
    = form_for(Concierge.new, :url => call_concierge_path(Concierge.get_latest_config), :html => {:class => 'well'}) do |f|
      %h3 Call Concierge
      %hr.zero
        %input.span2{:value => current_user.profile.phone, :type => "text", :name => 'phone_number'}
          %span.help-inline Press Call and Your Phone will Ring
          %button.btn.btn-primary{:type => "submit"} Call Concierge
          %br/
  / concierge
/ span3

app/views/shared/_settings.html.haml
.span3
  .well
    %ul.nav.nav-list#settings
      %li.nav-header Account Settings
      - if profiles? &&  !profiles_privacy?
        %li
          %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseOne" }
            %i.icon-home>
            Profile Info
        %li
          %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseTwo" }
            %i.icon-shopping-cart>
            Billing Info
        %li
          %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseThree"}
            %i.icon-envelope>
            Notifications
        %li
          %a.accordion-toggle{"data-parent" => "#accordion2", "data-toggle" => "collapse", :href => "#collapseFour"}
            %i.icon-lock>
            Change Password
      - else
        %li{:class => "#{'active' if profiles_edit?}"}
          %a{ :href => "#{edit_profile_path(current_user.permalink, :value => 'profile info')}" }
            %i.icon-home>
            Profile Info
        %li
          %a{ :href => "#{edit_profile_path(current_user.permalink, :value => 'billing info')}" }
            %i.icon-shopping-cart>
            Billing Info
        %li
          %a{ :href => "#{edit_profile_path(current_user.permalink, :value => 'notifications')}" }
            %i.icon-envelope>
            Notifications
        %li
          %a{ :href => "#{edit_profile_path(current_user.permalink, :value => 'change password')}" }
            %i.icon-lock>
            Change Password
      %li.nav-header Privacy Settings
      %li{:class => "#{'active' if profiles_privacy?}"}
        %a{:href => "#{edit_privacy_profiles_path}"}
          %i.icon-lock>
          Privacy
      %li.nav-header Order History
      %li{:class => "#{'active' if orders?}"}
        %a{:href => orders_path}
          %i.icon-gift>
          Orders
/ span3

app/views/shared/_verification_messages.html.haml
- if !current_user.verified?
  - if current_user.submitted_for_verification?
    #errorExplanation.alert.alert-flash
      %a.close{"data-dismiss" => "alert"}×
      %h4.alert-heading
        You have submitted your account verification and it is in progress.
  -else
    #errorExplanation.alert.alert-flash
      %a.close{"data-dismiss" => "alert"}×
      %h4.alert-heading
        You have not verified your account.
        %a.btn.btn-primary{"data-toggle" => "modal", :href => "#user-verification"} Verify now
    #user-verification.modal.hide.fade{:style => "display:none;"}
      .modal-header
        %a.close{"data-dismiss" => "modal", :href => "#"} ×
        %h3 Verification form
      .modal-body
        = form_for(Verfication.new ,:html => {:class => 'form-horizontal'}) do |f|

          %fieldset
            .control-group
              %label.control-label{:for => "input01"} Question 1 :
              .controls
                "#{Question.question1}"
            .control-group
              %label.control-label{:for => "input01"} Answer :
              .controls
                %input#input01.input-xlarge{:type => "text",:name => 'verfication[answer1]'}
            .control-group
              %label.control-label{:for => "input01"} Question 2 :
              .controls
                "#{Question.question2}"
            .control-group
              %label.control-label{:for => "input01"} Answer :
              .controls
                %input#input01.input-xlarge{:type => "text",:name => 'verfication[answer2]'}
            .control-group
              %label.control-label{:for => "input01"} Question 3 :
              .controls
                "#{Question.question3}"
            .control-group
              %label.control-label{:for => "input01"} Answer :
              .controls
                %input#input01.input-xlarge{:type => "text",:name => 'verfication[answer3]'}
                %input#input01.input-xlarge{:type => "hidden",:name => 'verfication[user_id]',:value => current_user.id}
              .form-actions
                %button.btn.btn-primary{:type => "submit"}Submit
                %button.btn{"data-dismiss" => "modal", :type => "reset"} Cancel