config/routes.rb
Affluence2::Application.routes.draw do

  

  
  resources :discussions, :only => [:index, :new, :create, :update] do
    end
  get "activities/index"

  get "activities/connections"

  get "offers/index"

  get "offers/new"

  get "offers/edit"

  get "offers/create"

  get "offers/update"

  get "offers/show"

  ActiveAdmin.routes(self)

  match 'home' => 'home#index'

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => 'passwords', :invitations => 'users/invitations'}
  devise_scope :user do
    get "/users/sign_in" => "welcome#index"

    get "/users/invitations/contacts" => "users/invitations#get_contacts", :as => :get_contacts
    post "/users/invitations/contacts" => "users/invitations#import_contacts", :as => :import_contacts

    match "/users/invitations/contacts_provider_callback" => "users/invitations#contacts_provider_callback", :as => :contacts_provider_callback

  end
 
  match "states_of_country", :to => "application#states_of_country"

  resources :users, :only => :show do
    resources :conversations, :only => [:index, :show, :new, :create, :update] do
      get :autocomplete_profile_full_name, :on => :collection
      get :archive
      get :unarchive
      get :confirm, :on => :collection
    end
    resources :photo_streams do
      post :create_photo
      delete 'photo/:id' => :destroy_photo, :as => 'photo'
    end
  end

  resources :photo_streams  

  resources :events do
    member do
      post :register
      get :delete_image
    end
    collection do
      get :home_page_events
      get :landing_page_events
      get :confirm
      get :events_schedules
    end
  end

  resources :home do

  end

  resources :verfications

  resources :photos

  resources :concierges do
    member do
      post :call
    end
  end

  resources :profiles  do
    collection do
      get :confirm
      get :confirm_credit_card_info
      get :profile_session
      get :check_avilability
      get :autocomplete_interest_name 
      get :autocomplete_expertise_name
      get :autocomplete_association_name
      get :update_notifications
      get :user_plan
      get :billing_info_confirm
      get :billing_info_update_confirm
      post :update_plan
      get :edit_privacy
      get :update_privacy
      get :cancel_membership
      get :delete_account
    end

    member do
      get :set_notification_complete
    end
  end

  resources :members, :except => [:show] do
    collection do
      get :latest
      get :find_members
      get :search
      get :delete_connection
    end
  end

  resources :offers do
    collection do
      get :latest
      get :confirm
    end
    member do
      get :activate
    end
  end

  resources :activities do
    collection do
      get :latest
    end
  end

  resources :orders
  resources :wineshares
  resources :welcome
  
  resources :twilio_calls do
    collection do
      get :receive_call
      post :status_call_back
    end
  end

  resources :promotions do
    member do
      get :become_premium_member
    end
  end

  match "api/user/sign_in" => "api#user_sign_in", :ssl => :required
  match "api/postback" => "api#postback", :ssl => :required
  match "api/callback_test" => "api#callback_test", :ssl => :required
  post "api/vincompass/validate_tokens" => "api#validate_tokens", :ssl => :required
  post "api/vincompass/authorize/application" => "api#authorize_application", :ssl => :required
  post "api/vincompass/authorize/user" => "api#authorize_user", :ssl => :required
  post "api/vincompass/activity_post" => "api#activity_post", :ssl => :required
  post "api/vincompass/v2/activity_post" => "api#activity_post_v2", :ssl => :required

  root :to => 'welcome#index'

  match '*url' => 'welcome#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!, :update_unread_messages_count

  def index

  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- content_for :verification_message do
  = render 'shared/verification_messages'

.span9
  %div
    %h2
      %small new
      Members
    %hr.zero
      %ul.thumbnails#latest_members
        %li
          #spinner
            = image_tag 'ajax-loader.gif', :class => 'ajax-loader'
            %p Loading....
      %p.pull-right
        = link_to "see more members", search_members_path    
      %br/
      %br/
  %div
    %h2
      %small new
      Events
    %hr.zero
      %ul.thumbnails#latest_events
        %li
          #spinner
            = image_tag 'ajax-loader.gif', :class => 'ajax-loader'
            %p Loading....
      %p.pull-right
        %a{:href => "/events"} see more events
      %br/
      %br/
  %div
    %h2
      %small new
      Offers
    %hr.zero
      %ul.thumbnails#latest_offers
        %li
          #spinner
            = image_tag 'ajax-loader.gif', :class => 'ajax-loader'
            %p Loading....
      %p.pull-right
        = link_to "see more offers", offers_path
      %br/
      %br/
  #activity
    .row.zero-row
      .span5
        %h2 Activity
      .span4
        .btn-group.pull-right{"data-toggle" => "buttons-radio"}
          %button.get-activities.btn.btn-small.btn-primary.active#entire_network Entire Network
          %button.get-activities.btn.btn-small.btn-primary#my_connections my Connections
    %hr.zero
      %table.table.table-striped
        %tbody#latest_activities
          %tr
            %td.span1
              #spinner
                = image_tag 'ajax-loader.gif', :class => 'ajax-loader'
                %p Loading....
      %p{:id => 'ajax-more-activities'}
        = image_tag 'ajax-loader.gif', :class => 'ajax-loader', :style => 'margin:0 0 0 48%;display:none', :align => 'middle'
        = button_tag 'more activities', :class => 'btn more-activities span9', :type => 'button', :style => "margin:0px"
           
-content_for :javascripts do
  :javascript
    $(function () {
      // gets latest members
      $("#latest_members").load("#{latest_members_path}");
      $("#latest_offers").load("#{latest_offers_path}");
      $("#latest_events").load("#{home_page_events_events_path}", function(){
         getActivities({"type" : "Entire Network"}, false);
      });





      $('.more-activities').hide();



      
      $('.get-activities').click(function(){
        $('.ajax-loader').hide();
        if(!$(this).hasClass('active')){
         getActivities({"type" : $(this).text()}, false);
         $('.more-activities').text("more activities");
        }
         $('.more-activities').attr("disabled", false);
      });

      $('.more-activities').click(function(){
         getActivities({"type" : $('.get-activities.active').text()}, true);
      });

      $('a[rel=tooltip]').tooltip({
        live: true
      });

    });



  