config/routes.rb
Affluence2::Application.routes.draw do

  

  
  resources :discussions, :only => [:index, :new, :create, :update] do
    end
  get "activities/index"

  get "activities/connections"

  get "offers/index"

  get "offers/new"

  get "offers/edit"

  get "offers/create"

  get "offers/update"

  get "offers/show"

  ActiveAdmin.routes(self)

  match 'home' => 'home#index'

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => 'passwords', :invitations => 'users/invitations'}
  devise_scope :user do
    get "/users/sign_in" => "welcome#index"

    get "/users/invitations/contacts" => "users/invitations#get_contacts", :as => :get_contacts
    post "/users/invitations/contacts" => "users/invitations#import_contacts", :as => :import_contacts

    match "/users/invitations/contacts_provider_callback" => "users/invitations#contacts_provider_callback", :as => :contacts_provider_callback

  end
 
  match "states_of_country", :to => "application#states_of_country"

  resources :users, :only => :show do
    resources :conversations, :only => [:index, :show, :new, :create, :update] do
      get :autocomplete_profile_full_name, :on => :collection
      get :archive
      get :unarchive
      get :confirm, :on => :collection
    end
    resources :photo_streams do
      post :create_photo
      delete 'photo/:id' => :destroy_photo, :as => 'photo'
    end
  end

  resources :photo_streams  

  resources :events do
    member do
      post :register
      get :delete_image
    end
    collection do
      get :home_page_events
      get :landing_page_events
      get :confirm
      get :events_schedules
    end
  end

  resources :home do

  end

  resources :verfications

  resources :photos

  resources :concierges do
    member do
      post :call
    end
  end

  resources :profiles  do
    collection do
      get :confirm
      get :confirm_credit_card_info
      get :profile_session
      get :check_avilability
      get :autocomplete_interest_name 
      get :autocomplete_expertise_name
      get :autocomplete_association_name
      get :update_notifications
      get :user_plan
      get :billing_info_confirm
      get :billing_info_update_confirm
      post :update_plan
      get :edit_privacy
      get :update_privacy
      get :cancel_membership
      get :delete_account
    end

    member do
      get :set_notification_complete
    end
  end

  resources :members, :except => [:show] do
    collection do
      get :latest
      get :find_members
      get :search
      get :delete_connection
    end
  end

  resources :offers do
    collection do
      get :latest
      get :confirm
    end
    member do
      get :activate
    end
  end

  resources :activities do
    collection do
      get :latest
    end
  end

  resources :orders
  resources :wineshares
  resources :welcome
  
  resources :twilio_calls do
    collection do
      get :receive_call
      post :status_call_back
    end
  end

  resources :promotions do
    member do
      get :become_premium_member
    end
  end

  match "api/user/sign_in" => "api#user_sign_in", :ssl => :required
  match "api/postback" => "api#postback", :ssl => :required
  match "api/callback_test" => "api#callback_test", :ssl => :required
  post "api/vincompass/validate_tokens" => "api#validate_tokens", :ssl => :required
  post "api/vincompass/authorize/application" => "api#authorize_application", :ssl => :required
  post "api/vincompass/authorize/user" => "api#authorize_user", :ssl => :required
  post "api/vincompass/activity_post" => "api#activity_post", :ssl => :required
  post "api/vincompass/v2/activity_post" => "api#activity_post_v2", :ssl => :required

  root :to => 'welcome#index'

  match '*url' => 'welcome#index'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessor :offer_image
  has_one :promotion, :as => :promotionable, :dependent => :destroy

  validates_presence_of :title, :description, :link

  # Select N top users. Returns 10 entries when called without arguments.
  #   User.top.all.size    # => 10
  #   User.top(2).all.size # => 2
  #
  scope :active, where(:active => true)
  scope :dinning, where(:category => 'Dinning')
  scope :travel, where(:category => 'Travel')
  scope :financial, where(:category => 'Financial')
  scope :shopping, where(:category => 'Shopping')
  scope :services, where(:category => 'Services')

  scope :latest, lambda { |*args| {:limit => (args.size > 0 ? args[0] : 3), :order => "id desc"} }


end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_filter :authenticate_user!


  def latest
    @latest_offers = Offer.latest
    render :partial => 'latest'
  end

  def index
    @featured_offers = Offer.where("featured = true", :order => 'created_at asc')
    @travel_offers = Offer.where("category like 'Travel'", :order => 'created_at asc')
    @services_offers = Offer.where("category like 'Services'", :order => 'created_at asc')
    @dinning_offers = Offer.where("category like 'Dinning'", :order => 'created_at asc')
    @shopping_offers = Offer.where("category like 'Shopping'", :order => 'created_at asc')
    @financial_offers = Offer.where("category like 'Financial'", :order => 'created_at asc')
  end

  def activate
    offer = Offer.find(params[:id])
    if current_user.plan == 'free'
      flash[:error] = "You need to Become a Premium Member to activate this offer"
      redirect_to offers_path and return
    end
    offer.promotion.activate_promotion_for_member(current_user)
    Activity.create_user_offer(current_user, offer)
    reset_session_activity 
    redirect_to offer.link
  end

  # will be called when free user tries to subscribe before offer activation.
  def confirm
    begin
      @result = Braintree::TransparentRedirect.confirm(request.query_string)
      if @result.success?
        current_user.update_user_with_plan_and_braintree_id(session[:user_plan], @result.customer.id)
        session[:user_plan]=nil
        flash[:success] = "You have successfully converted to paid member. Now you can activate to offer by clicking on the Activate button"
        redirect_to offers_path
      else
        flash[:error] = "Your payment was not success. Check your card information."
        redirect_to offers_path
      end
    rescue
      flash[:error] = "Your payment was not success. Check your card information."
      redirect_to offers_path
    end
  end


end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_latest.html.haml
- @latest_offers.each do |offer|
  %li.span3
    .thumbnail
      = image_tag display_image(offer.promotion.photos)
      .caption
        %h5= offer.title
        %p= offer.description
        %p
          %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
            %i.icon-ok.icon-white
            Activate
- if current_user.plan == 'free'
  = render :partial => 'shared/billing_info', :locals => {:div_id => 'billing_info' , :callback_url => confirm_offers_url}
  :javascript
    $('.offer-register-button').click(function(){
      var offer_id = this.id.split('_')[1]
      //alert(event_id) ;
      $.ajax({
                    url: "/promotions/"+offer_id+"/become_premium_member",
                    data:'promotion=offer',
                    //async: false,
                    success:function(data){
                      $('#register-div').empty();
                      $('#billing_info').html(data);
                      //alert('Load was performed.');
                    },
                    dataType:'html'
                    });
      //$('#register-div').modal('show');
    });

app/views/offers/create.html.haml
%h1 Offers#create
%p Find me in app/views/offers/create.html.haml

app/views/offers/edit.html.haml
%h1 Offers#edit
%p Find me in app/views/offers/edit.html.haml

app/views/offers/index.html.haml
- href_link = current_user.plan == 'free' ? true : false
.row
  .span3
    .well
      %ul.nav.nav-list
        %li.nav-header Filter
        %li.active
          %a{:href => "#featured"}
            %i.icon-adjust>
            Featured
        %li
          %a{:href => "#travel"}
            %i.icon-plane>
            Travel
        %li
          %a{:href => "#services"}
            %i.icon-cog>
            Services
        %li
          %a{:href => "#financial"}
            %i.icon-lock>
            Financial
        %li
          %a{:href => "#shopping"}
            %i.icon-shopping-cart>
            Shopping
        %li
          %a{:href => "#dinning"}
            %i.icon-leaf>
            Dinning
  / span3
  .span9
    #featured
      %h2 Featured Offers
      %hr.zero
        %ul.thumbnails
          - if @featured_offers.length >= 1
            - @featured_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..." #activate_offer_path(offer.id)
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
        %ul.thumbnails
          - if @featured_offers.length > 3
            - @featured_offers[3..5].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Featured
    #travel
      %h2 Travel
      %hr.zero
        %ul.thumbnails
          - if @travel_offers.length >= 1
            - @travel_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Travel
    #services
      %h2 Services
      %hr.zero
        %ul.thumbnails
          - if @services_offers.length >= 1
            - @services_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Services
    #financial
      %h2 Financial
      %hr.zero
        %ul.thumbnails
          - if @financial_offers.length >= 1
            - @financial_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Financial
    #shopping
      %h2 Shopping
      %hr.zero
        %ul.thumbnails
          - if @shopping_offers.length >= 1
            - @shopping_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Shopping
    #dinning
      %h2 Dinning
      %hr.zero
        %ul.thumbnails
          - if @dinning_offers.length >= 1
            - @dinning_offers[0..2].each do |offer|
              %li.span3
                .thumbnail
                  = image_tag offer.promotion.offer_image.image.url(:medium)
                  .caption
                    %h5= "#{offer.title[0..30]}"
                    %p= "#{offer.description[0..48]}..."
                    %p
                      %a.btn.btn-info{"data-toggle" => "modal", :href => offer_activation_link(current_user,offer), :id => "offer_#{offer.id}", :class => "offer-register-button"}
                        %i.icon-ok.icon-white
                        Activate
    / Dinning
  / span9
- if current_user.plan == 'free'
  = render :partial => 'shared/billing_info', :locals => {:div_id => 'billing_info' , :callback_url => confirm_offers_url}
  :javascript
    $('.offer-register-button').click(function(){
      var offer_id = this.id.split('_')[1]
      //alert(event_id) ;
      $.ajax({
                    url: "/promotions/"+offer_id+"/become_premium_member",
                    data:'promotion=offer',
                    //async: false,
                    success:function(data){
                      $('#billing_info').html(data);
                      //alert('Load was performed.');
                    },
                    dataType:'html'
                    });
      //$('#register-div').modal('show');
    });
- content_for :javascript

app/views/offers/latest.js.erb
$("#latest_offers").html("<%= escape_javascript(render( :partial => 'latest' )) %>");

app/views/offers/new.html.haml
%h1 Offers#new
%p Find me in app/views/offers/new.html.haml

app/views/offers/show.html.haml
%h1 Offers#show
%p Find me in app/views/offers/show.html.haml

app/views/offers/update.html.haml
%h1 Offers#update
%p Find me in app/views/offers/update.html.haml